config is getting better

diff --git a/bashrc_custom b/bashrc_custom
--- a/bashrc_custom
+++ b/bashrc_custom
@@ -373,126 +373,104 @@ function whatsmyip ()
 	# External IP Lookup
 	echo -n "External IP: " ; wget http://smart-ip.net/myip -O - -q
 }
+hex_to_ansi() {
+    local hex=$1
+    local r g b
+
+    # Remove the '#' if present
+    hex=${hex#\#}
+
+    # Convert hex to RGB
+    r=$((16#${hex:0:2}))
+    g=$((16#${hex:2:2}))
+    b=$((16#${hex:4:2}))
+
+    # Convert RGB to ANSI 256 color code
+    local ansi_code
+    ansi_code=$((36 * (r * 5 / 255) + 6 * (g * 5 / 255) + (b * 5 / 255) + 16))
+
+    echo "\033[38;5;${ansi_code}m"
+}
 
 #######################################################
 # Set the ultimate amazing command prompt
 #######################################################
 
 alias cpu="grep 'cpu ' /proc/stat | awk '{usage=(\$2+\$4)*100/(\$2+\$4+\$5)} END {print usage}' | awk '{printf(\"%.1f\n\", \$1)}'"
-function __setprompt
-{
-	local LAST_COMMAND=$? # Must come first!
+function __setprompt {
+    local LAST_COMMAND=$?  # Must come first!
 
-	# Define colors
-	local LIGHTGRAY="\033[0;37m"
-	local WHITE="\033[1;37m"
-	local BLACK="\033[0;30m"
-	local DARKGRAY="\033[1;30m"
-	local RED="\033[0;31m"
-	local LIGHTRED="\033[1;31m"
-	local GREEN="\033[0;32m"
-	local LIGHTGREEN="\033[1;32m"
-	local BROWN="\033[0;33m"
-	local YELLOW="\033[1;33m"
-	local BLUE="\033[0;34m"
-	local LIGHTBLUE="\033[1;34m"
-	local MAGENTA="\033[0;35m"
-	local LIGHTMAGENTA="\033[1;35m"
-	local CYAN="\033[0;36m"
-	local LIGHTCYAN="\033[1;36m"
-	local NOCOLOR="\033[0m"
+    # Define 24-bit color escape sequences using your palette
+    local FG_PRIMARY="\[\e[38;2;220;223;228m\]"    # palette 7 / bright white (primary text)
+    local FG_DISABLED="\[\e[38;2;92;99;112m\]"       # palette 1 / bright black (disabled text)
+    local FG_HIGHLIGHT="\[\e[38;2;71;78;93m\]"       # palette 2 / bright green (highlight background)
+    local ACCENT_LIGHTBLUE="\[\e[38;2;86;182;194m\]"  # palette 3 / light blue accent
+    local PRIMARY_BLUE="\[\e[38;2;97;175;239m\]"      # palette 4 / primary blue
+    local PRIMARY_PURPLE="\[\e[38;2;198;120;221m\]"   # palette 5 / primary purple & bright red/magenta
+    local LIGHTEST_BLUE="\[\e[38;2;112;184;194m\]"     # palette 6 / lightest blue accent
+    local NOCOLOR="\[\e[0m\]"
 
-	# Show error exit code if there is one
-	if [[ $LAST_COMMAND != 0 ]]; then
-		# PS1="\[${RED}\](\[${LIGHTRED}\]ERROR\[${RED}\])-(\[${LIGHTRED}\]Exit Code \[${WHITE}\]${LAST_COMMAND}\[${RED}\])-(\[${LIGHTRED}\]"
-		PS1="\[${DARKGRAY}\](\[${LIGHTRED}\]ERROR\[${DARKGRAY}\])-(\[${RED}\]Exit Code \[${LIGHTRED}\]${LAST_COMMAND}\[${DARKGRAY}\])-(\[${RED}\]"
-		if [[ $LAST_COMMAND == 1 ]]; then
-			PS1+="General error"
-		elif [ $LAST_COMMAND == 2 ]; then
-			PS1+="Missing keyword, command, or permission problem"
-		elif [ $LAST_COMMAND == 126 ]; then
-			PS1+="Permission problem or command is not an executable"
-		elif [ $LAST_COMMAND == 127 ]; then
-			PS1+="Command not found"
-		elif [ $LAST_COMMAND == 128 ]; then
-			PS1+="Invalid argument to exit"
-		elif [ $LAST_COMMAND == 129 ]; then
-			PS1+="Fatal error signal 1"
-		elif [ $LAST_COMMAND == 130 ]; then
-			PS1+="Script terminated by Control-C"
-		elif [ $LAST_COMMAND == 131 ]; then
-			PS1+="Fatal error signal 3"
-		elif [ $LAST_COMMAND == 132 ]; then
-			PS1+="Fatal error signal 4"
-		elif [ $LAST_COMMAND == 133 ]; then
-			PS1+="Fatal error signal 5"
-		elif [ $LAST_COMMAND == 134 ]; then
-			PS1+="Fatal error signal 6"
-		elif [ $LAST_COMMAND == 135 ]; then
-			PS1+="Fatal error signal 7"
-		elif [ $LAST_COMMAND == 136 ]; then
-			PS1+="Fatal error signal 8"
-		elif [ $LAST_COMMAND == 137 ]; then
-			PS1+="Fatal error signal 9"
-		elif [ $LAST_COMMAND -gt 255 ]; then
-			PS1+="Exit status out of range"
-		else
-			PS1+="Unknown error code"
-		fi
-		PS1+="\[${DARKGRAY}\])\[${NOCOLOR}\]\n"
-	else
-		PS1=""
-	fi
+    # Start prompt with error info if last command failed
+    if [[ $LAST_COMMAND != 0 ]]; then
+        PS1="${FG_DISABLED}${PRIMARY_PURPLE}ERROR${FG_DISABLED} ${PRIMARY_PURPLE}Exit Code ${FG_PRIMARY}${LAST_COMMAND}${FG_DISABLED}"
+        case $LAST_COMMAND in
+            1) PS1+=" General error";;
+            2) PS1+=" Missing keyword, command, or permission problem";;
+            126) PS1+=" Permission problem or command is not executable";;
+            127) PS1+=" Command not found";;
+            128) PS1+=" Invalid argument to exit";;
+            129) PS1+=" Fatal error signal 1";;
+            130) PS1+=" Script terminated by Control-C";;
+            131) PS1+=" Fatal error signal 3";;
+            132) PS1+=" Fatal error signal 4";;
+            133) PS1+=" Fatal error signal 5";;
+            134) PS1+=" Fatal error signal 6";;
+            135) PS1+=" Fatal error signal 7";;
+            136) PS1+=" Fatal error signal 8";;
+            137) PS1+=" Fatal error signal 9";;
+            *) PS1+=" Unknown error code";;
+        esac
+        PS1+="${NOCOLOR}\n"
+    else
+        PS1=""
+    fi
 
-	# Date
-	PS1+="\[${DARKGRAY}\](\[${CYAN}\]\$(date +%a) $(date +%b-'%-m')" # Date
-	PS1+="${BLUE} $(date +'%-I':%M:%S%P)\[${DARKGRAY}\])-" # Time
+    # Date and time segment
+    PS1+="${FG_DISABLED}${ACCENT_LIGHTBLUE}\$(date +%a) $(date +%b-%-m) ${PRIMARY_BLUE}\$(date +'%-I:%M:%S%P')${FG_DISABLED}"
 
-	# CPU
-	PS1+="(\[${MAGENTA}\]CPU $(cpu)%"
+    # CPU usage (assuming function 'cpu' is defined)
+    PS1+=" ${PRIMARY_PURPLE}CPU \$(cpu)%"
 
-	# Jobs
-	PS1+="\[${DARKGRAY}\]:\[${MAGENTA}\]\j"
+    # Number of background jobs
+    PS1+=" ${FG_DISABLED}:${PRIMARY_PURPLE}\j"
 
-	# Network Connections (for a server - comment out for non-server)
-	PS1+="\[${DARKGRAY}\]:\[${MAGENTA}\]Net $(awk 'END {print NR}' /proc/net/tcp)"
+    # Network connections count
+    PS1+=" ${FG_DISABLED}:${PRIMARY_PURPLE}Net \$(awk 'END {print NR}' /proc/net/tcp)${FG_DISABLED}"
 
-	PS1+="\[${DARKGRAY}\])-"
+    # User and host segment
+    local SSH_IP=$(echo $SSH_CLIENT | awk '{ print $1 }')
+    local SSH2_IP=$(echo $SSH2_CLIENT | awk '{ print $1 }')
+    PS1+=" ${FG_PRIMARY}\u"
+    [[ $SSH_IP || $SSH2_IP ]] && PS1+="@\h"
 
-	# User and server
-	local SSH_IP=`echo $SSH_CLIENT | awk '{ print $1 }'`
-	local SSH2_IP=`echo $SSH2_CLIENT | awk '{ print $1 }'`
-	if [ $SSH2_IP ] || [ $SSH_IP ] ; then
-		PS1+="(\[${RED}\]\u@\h"
-	else
-		PS1+="(\[${RED}\]\u"
-	fi
+    # Current working directory
+    PS1+=" ${PRIMARY_BLUE}\w${FG_DISABLED}"
 
-	# Current directory
-	PS1+="\[${DARKGRAY}\]:\[${BROWN}\]\w\[${DARKGRAY}\])-"
+    # Directory file info: total size and number of files
+    PS1+=" ${LIGHTEST_BLUE}\$(/bin/ls -lah | /bin/grep -m 1 total | /bin/sed 's/total //')"
+    PS1+=" ${LIGHTEST_BLUE}\$(/bin/ls -A -1 | /usr/bin/wc -l)${FG_DISABLED}\n"
 
-	# Total size of files in current directory
-	PS1+="(\[${GREEN}\]$(/bin/ls -lah | /bin/grep -m 1 total | /bin/sed 's/total //')\[${DARKGRAY}\]:"
+    # Prompt symbol
+    if [[ $EUID -ne 0 ]]; then
+        PS1+="${PRIMARY_BLUE}>${NOCOLOR} "
+    else
+        PS1+="${PRIMARY_PURPLE}>${NOCOLOR} "
+    fi
 
-	# Number of files
-	PS1+="\[${GREEN}\]\$(/bin/ls -A -1 | /usr/bin/wc -l)\[${DARKGRAY}\])"
-
-	# Skip to the next line
-	PS1+="\n"
-
-	if [[ $EUID -ne 0 ]]; then
-		PS1+="\[${GREEN}\]>\[${NOCOLOR}\] " # Normal user
-	else
-		PS1+="\[${RED}\]>\[${NOCOLOR}\] " # Root user
-	fi
-
-	# PS2 is used to continue a command using the \ character
-	PS2="\[${DARKGRAY}\]>\[${NOCOLOR}\] "
-
-	# PS3 is used to enter a number choice in a script
-	PS3='Please enter a number from above list: '
-
-	# PS4 is used for tracing a script in debug mode
-	PS4='\[${DARKGRAY}\]+\[${NOCOLOR}\] '
+    # Set secondary prompt variables
+    PS2="${FG_DISABLED}>${NOCOLOR} "
+    PS3='Please enter a number from above list: '
+    PS4="${FG_DISABLED}+${NOCOLOR} "
 }
-PROMPT_COMMAND='__setprompt'
+PROMPT_COMMAND=__setprompt
+
